main/urls.py
from django.urls import path
from . import views
from .views import UserQuestionsListView

urlpatterns = [
    path('',views.home,name='stackoverflow-home'),
    path('detail/<int:id>/',views.detail,name='stackoverflow-detail_page'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('save-upvote',views.save_upvote,name='save-upvote'),
    path('save-downvote',views.save_downvote,name='save-downvote'),
    path('ask-question',views.ask_form,name='ask-question'),
    path('tag/<str:tag>',views.tag,name='tag'),
    path('profile/',views.TotalProfile,name='profile'),
    path('tags/',views.tags,name='tags'),
    path('user/<str:username>', UserQuestionsListView.as_view(), name='user-qstns'),
    
]

stackoverflow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/',user_views.register, name='register'),
    
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    detail = models.TextField()
    tags = models.TextField(default='')
    add_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    detail = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail

class Comment(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    comment = models.TextField(default='')
    add_time = models.DateTimeField(auto_now_add=True)

class UpVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upvote_user')
    

class DownVote(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='downvote_user')
    

main/forms.py
from django.forms import ModelForm
from .models import Answer, Question

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ('detail',)

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=('title','detail','tags')

main/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404
from django.http import JsonResponse
from .models import Question, Answer, Comment, UpVote, DownVote
from django.core.paginator import Paginator
from .forms import AnswerForm, QuestionForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.db.models import Count
from users.forms import UserUpdateForm, ProfileUpdateForm
from django.views.generic import ListView

def home(request):
    if 'q' in request.GET:
        q=request.GET['q']
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(title__icontains=q).order_by('-id')
    else:
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-id')
    paginator=Paginator(quests,5)
    page_num = request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'home.html',{'quests':quests})


class UserQuestionsListView(ListView):
	model = Question
	template_name = "user-qstns.html"
	context_object_name = "Question"
	paginate_by = 5

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Question.objects.filter(user=user).order_by('-id')


def detail(request,id):
    quest=Question.objects.get(pk=id)
    tags=quest.tags.split(',')
    answers=Answer.objects.filter(question=quest)
    answerform=AnswerForm
    if request.method=='POST':
        answerData=AnswerForm(request.POST)
        if answerData.is_valid:
            answer=answerData.save(commit=False)
            answer.question=quest
            answer.user=request.user
            answer.save()
            messages.success(request,'Answer has been submitted!')
    return render(request,'detail.html',{
        'quest':quest,
        'tags':tags,
        'answers':answers,
        'answerform':answerform,
    })


def save_comment(request):
    if request.method=='POST':
        comment=request.POST['comment']
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            comment=comment,
            user=user
        )
        return JsonResponse({'bool':True})

def save_upvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=UpVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            UpVote.objects.create(
                answer=answer,
                user=user
            )
        return JsonResponse({'bool':True})

def save_downvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=DownVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            DownVote.objects.create(
                answer=answer,
                user=user
            )
        return JsonResponse({'bool':True})

def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
    return render(request,'ask-question.html',{'form':form})

def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'tag.html',{'quests':quests,'tag':tag})

def TotalProfile(request):
    quests=Question.objects.filter(user=request.user).order_by('-id')
    answers=Answer.objects.filter(user=request.user).order_by('-id')
    comments=Comment.objects.filter(user=request.user).order_by('-id')
    upvotes=UpVote.objects.filter(user=request.user).order_by('-id')
    downvotes=DownVote.objects.filter(user=request.user).order_by('-id')
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile has been modified!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    return render(request,'profile.html',{
        'u_form':u_form,
        'p_form':p_form,
        'quests':quests,
        'answers':answers,
        'comments':comments,
        'upvotes':upvotes,
        'downvotes':downvotes,
    })

def tags(request):
    quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    return render(request,'tags.html',{'tags':tag_with_count})
        
        

main/templates/ask-question.html
{% extends 'base.html' %}
{% block title %}Ask Question{% endblock %}
{% block content %}
<div class="container">
    <div class="card mt-5">
        <h5 class="card-header">Ask Question</h5>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{form.as_table}}
                    <tr>
                        <td colspan="2">
                            <button class="btn btn-primary">Submit</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{quest.title}}{% endblock %}
{% block content %}
    <div class="container">
        <article class="media content-section">
            <img class="rounded-circle article-img" src= "{{ quest.user.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-qstns' quest.user.username %}">{{ quest.user.username }}</a>
                <small class="text-muted">{{ quest.add_time|date:'d/m/Y' }}</small>
                </div>
                <h2 class="article-title">{{ quest.title }}</h2>
                <p class="article-content">{{ quest.detail }}</p>
            </div>
        </article>
        <p>
            tags:
            {% for tag in tags %}
            <a href="/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
            {% endfor %}
        </p>
        <hr/>
        {% for answer in answers %}
        <div class="row">
            <div class="col-1">
                <div class="upvote">
                    <strong class="upvote-count-{{answer.id}}">{{answer.upvote_set.count}}</strong><br/>
                    <span class="text-success">
                        <i class="fa fa-arrow-up fa-2x upvote-click" data-answer="{{answer.id}}"></i>
                    </span>
                </div>
                <div class="downvote mt-3">
                    <span class="text-danger">
                        <i class="fa fa-arrow-down fa-2x downvote-click" data-answer="{{answer.id}}"></i>
                    </span><br/>   
                    <strong class="downvote-count-{{answer.id}}">{{answer.downvote_set.count}}</strong> 
                </div>
            </div>
            <div class="col-11">
                <p>
                    {{answer.detail}}
                </p>
                <p>
                    <a href="#" class="mr-3">{{answer.user.username}}</a>
                    <span class="mr-3">
                        <span class="comment-count-{{answer.id}}">{{answer.comment_set.count}}</span> comments</span>
                    <span>{{answer.add_time|date:'m/d/Y'}}</span>
                </p>
                
                <h3 class="my-4">Comment</h3>
                <div class="comment-wrapper-{{answer.id}}">
                    {% for comment in answer.comment_set.all %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <p>{{comment.comment}}</p>
                            <p>
                                <a href="#">{{comment.user.username}}</a>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if user.is_authenticated %}
                <!-- Comment Form -->
                <div class="card my-3">
                    <h6 class="card-header">Add comment</h6>
                    <div class="card-body">
                        <textarea class="form-control comment-text-{{answer.id}}"></textarea>
                        <button type="button" data-answer="{{answer.id}}" class="btn btn-dark my-3 save-comment">Submit</button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <hr/>
        {% endfor %}
        {% if user.is_authenticated %}
        {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered">
                {{answerform.as_table}}
                <tr>
                    <td colspan="2">
                        <input type="submit" class="btn btn-dark" />
                    </td>
                </tr>
            </table>
        </form>
        {% endif %}
    </div>

    
    <script>
        $(document).ready(function(){
            $(".save-comment").on('click',function(){
                var _answerid=$(this).data('answer');
                var _comment=$(".comment-text-"+_answerid).val();
                $.ajax({
                    url:"/save-comment",
                    type:"post",
                    data:{
                        comment:_comment,
                        answerid:_answerid,
                        csrfmiddlewaretoken:"{{csrf_token}}"
                    },
                    dataType:'json',
                    beforeSend:function(){
                        $(".save-comment").addClass('disabled').text('Saving..');
                    },
                    success:function(res){
                        if(res.bool==true){
                            $(".comment-text-"+_answerid).val('');
                            var _html='<div class="card mb-3 animate__animated animate__bounce">\
                            <div class="card-body">\
                                <p>'+_comment+'</p>\
                                <p>\
                                    <a href="#">{{request.user}}</a>\
                                </p>\
                            </div>\
                        </div>';
                        $(".comment-wrapper-"+_answerid).append(_html);
                        var prevCount=$(".comment-count-"+_answerid).text();
                        $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
                        }
                        $(".save-comment").removeClass('disabled').text('Submit');
                    }
                });
            });

            $(".upvote-click").on('click',function(){
                var answerid=$(this).data('answer');   
                $.ajax({
                    url:"/save-upvote",
                    type:"post",
                    data:{
                        answerid:answerid,
                        csrfmiddlewaretoken:"{{csrf_token}}"
                    },
                    dataType:'json',
                    success:function(res){
                        var _prevupvote=$(".upvote-count-"+answerid).text();
                        if(res.bool==true){
                            $(".upvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                        }
                    }
                });
            });

            $(".downvote-click").on('click',function(){
                var answerid=$(this).data('answer');   
                $.ajax({
                    url:"/save-downvote",
                    type:"post",
                    data:{
                        answerid:answerid,
                        csrfmiddlewaretoken:"{{csrf_token}}"
                    },
                    dataType:'json',
                    success:function(res){
                        var _prevdownvote=$(".downvote-count-"+answerid).text();
                        if(res.bool==true){
                            $(".downvote-count-"+answerid).text(parseInt(_prevdownvote)+1);
                        }
                    }
                });
            });


        });
         
    </script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    
{% endblock %}

main/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel = "stylesheet" type="text/css" href="{% static 'main/style.css' %}">

	{% if title %}
		<title>{{title}}</title>
	{% else %}
		<title>Django</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
	    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	        <div class="container">
	          	<a class="navbar-brand mr-4" href="#">StackOverflow</a>
	          	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	          	<span class="navbar-toggler-icon"></span>
	          	</button>
	          	<div class="collapse navbar-collapse" id="navbarToggle">
	            	<div class="navbar-nav mr-auto">
	              		<a class="nav-item nav-link" href="{% url 'stackoverflow-home' %}">Home</a>
	              		<a class="nav-item nav-link" href="#">About</a>
	            	</div>
	            <!-- Navbar Right Side -->
	            	<div class="navbar-nav">
                    
                        
                        <a class="nav-item nav-link" href="/tags">Tags</a>
                        <a class="nav-item nav-link" href="/ask-question">Ask</a>
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                    </div>
	            </div>
	          </div>
	        </div>
	      </nav>
    </header>


    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>
                    <div class="input-group">
                        <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
                        <div class="input-group-append">
                        <button class="btn btn-dark btn-lg" type="submit" id="button-addon2">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <main role="main" class="container">
    {% for quest in quests %}
        <article class="media content-section">
        	<img class="rounded-circle article-img" src= "{{ quest.user.profile.image.url }}">
	        <div class="media-body">
	            <div class="article-metadata">
	                <a class="mr-2" href="{% url 'user-qstns' quest.user.username %}">{{ quest.user.username }}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
	                <small class="text-muted">{{ quest.add_time|date:"F d, Y" }}</small>
	            </div>
	            <h2><a class="article-title" href="/detail/{{quest.id}}">{{ quest.title }}</a></h2>
	            <p class="article-content">{{ quest.detail }}</p>
	         </div>
        </article>
    {% endfor %}
    </main>

    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
            {% endif %}
            {% for i in quests.paginator.page_range %}
            {% if quests.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            {% if quests.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
            {% endif %}
        </ul>
      </nav>
	

    <div id="google_translate_element"></div>



    
        <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit">

        </script>
    <script type="text/javascript">
        function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
    }
     </script>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body> 
</body>
</html>

main/templates/tag.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{tag}}{% endblock %}
{% block content %}
    <main role="main" class="container">
        <h1 class="mb-3">Questions related to {{tag}}({{quests.paginator.count}})</h1>
        {% for quest in quests %}
            <article class="media content-section">
                <img class="rounded-circle article-img" src= "{{ quest.user.profile.image.url }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{% url 'user-qstns' quest.user.username %}">{{ quest.user.username }}</a>
                        <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                        <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                        <small class="text-muted">{{ quest.add_time|date:"F d, Y" }}</small>
                    </div>
                    <h2><a class="article-title" href="/detail/{{quest.id}}">{{ quest.title }}</a></h2>
                    <p class="article-content">{{ quest.detail }}</p>
                </div>
            </article>
        {% endfor %}
    </main>

    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
            {% endif %}
            {% for i in quests.paginator.page_range %}
            {% if quests.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            {% if quests.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

main/templates/tags.html
{% extends 'base.html' %}
{% load static %}
{% block title %}All Tags{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        <div class="row">
            {% for tag in tags %}
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text"><a href="/tag/{{tag.name|slugify}}">{{tag.name}} 
                            <span class="badge badge-info">{{tag.count}}</span></a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/user-qstns.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel = "stylesheet" type="text/css" href="{% static 'main/style.css' %}">

	{% if title %}
		<title>{{title}}</title>
	{% else %}
		<title>Django</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
	    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	        <div class="container">
	          	<a class="navbar-brand mr-4" href="#">StackOverflow</a>
	          	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	          	<span class="navbar-toggler-icon"></span>
	          	</button>
	          	<div class="collapse navbar-collapse" id="navbarToggle">
	            	<div class="navbar-nav mr-auto">
	              		<a class="nav-item nav-link" href="{% url 'stackoverflow-home' %}">Home</a>
	              		<a class="nav-item nav-link" href="#">About</a>
	            	</div>
	            <!-- Navbar Right Side -->
	            	<div class="navbar-nav">
                    
                        
                        <a class="nav-item nav-link" href="/tags">Tags</a>
                        <a class="nav-item nav-link" href="/ask-question">Ask</a>
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                    </div>
	            </div>
	          </div>
	        </div>
	      </nav>
    </header>

    
    <main role="main" class="container">
        <h1 class="mb-3">Questions of {{view.kwargs.username}}({{page_obj.paginator.count}})</h1>
        {% for quest in Question %}
            <article class="media content-section">
                <img class="rounded-circle article-img" src= "{{ quest.user.profile.image.url }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="#">{{view.kwargs.username}}</a>
                        <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                        <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                        <small class="text-muted">{{ quest.add_time|date:"F d, Y" }}</small>
                    </div>
                    <h2><a class="article-title" href="/detail/{{quest.id}}">{{ quest.title }}</a></h2>
                    <p class="article-content">{{ quest.detail }}</p>
                 </div>
            </article>
        {% endfor %}
        </main>
        <nav class="my-3 container">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                {% endif %}
            </ul>
          </nav>
	

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body> 
</body>
</html>